export enum PermissionKey {
    USER_VIEW = 'users.view',
    USER_CREATE = 'users.create',
    USER_EDIT = 'users.update',
    USER_DELETE = 'users.delete',

    ROLE_VIEW = 'roles.view',
    ROLE_CREATE = 'roles.create',
    ROLE_EDIT = 'roles.update',
    ROLE_DELETE = 'roles.delete',

    BRANCH_VIEW = 'branch_view',
    BRANCH_CREATE = 'branch_create',
    BRANCH_EDIT = 'branch_edit',
    BRANCH_DELETE = 'branch_delete',

    DASHBOARD_VIEW = 'dashboard_view',

    SCHEDULE_VIEW = 'calendar.view',
    SCHEDULE_CREATE = 'calendar.create',
    SCHEDULE_EDIT = 'calendar.update',
    SCHEDULE_DELETE = 'calendar.delete',
    SCHEDULE_IMPORT = 'calendar.import',
    SCHEDULE_EXPORT = 'calendar.export',

    LESSON_VIEW = 'lessons.view',
    LESSON_CREATE = 'lessons.create',
    LESSON_EDIT = 'lessons.update',
    LESSON_DELETE = 'lessons.delete',
    LESSON_IMPORT = 'lessons.import',
    LESSON_EXPORT = 'lessons.export',

    CATEGORY_VIEW = 'category_view',
    CATEGORY_CREATE = 'category_create',
    CATEGORY_EDIT = 'category_edit',
    CATEGORY_DELETE = 'category_delete',

    STOCK_CHECK_VIEW = 'stock_check_view',
    STOCK_CHECK_CREATE = 'stock_check_create',
    STOCK_CHECK_EDIT = 'stock_check_edit',
    STOCK_CHECK_DELETE = 'stock_check_delete',
    STOCK_CHECK_EXPORT = 'stock_check_export',

    PRODUCT_VIEW = 'product_view',
    PRODUCT_CREATE = 'product_create',
    PRODUCT_EDIT = 'product_edit',
    PRODUCT_DELETE = 'product_delete',
    PRODUCT_CANCEL = 'product_cancel',
    PRODUCT_IMPORT = 'product_import',
    PRODUCT_EXPORT = 'product_export',

    INVOICE_VIEW = 'invoice_view',
    INVOICE_CREATE = 'invoice_create',
    INVOICE_VOID = 'invoice_void',
    INVOICE_EDIT = 'invoice_edit',
    INVOICE_IMPORT = 'invoice_import',
    INVOICE_EXPORT = 'invoice_export',
    INVOICE_PRINT = 'invoice_print',

    RETURN_VIEW = 'return_view',
    RETURN_PROCESS = 'return_process',
    RETURN_VOID = 'return_void',
    RETURN_EDIT = 'return_edit',
    RETURN_EXPORT = 'return_export',
    RETURN_PRINT = 'return_print',

    IMPORT_VIEW = 'import_view',
    IMPORT_CREATE = 'import_create',
    IMPORT_EDIT = 'import_edit',
    IMPORT_VOID = 'import_void',
    IMPORT_IMPORT = 'import_import',
    IMPORT_EXPORT = 'import_export',
    IMPORT_PRINT = 'import_print',

    CUSTOMER_VIEW = 'customer_view',
    CUSTOMER_CREATE = 'customer_create',
    CUSTOMER_EDIT = 'customer_edit',
    CUSTOMER_DELETE = 'customer_delete',
    CUSTOMER_IMPORT = 'customer_import',
    CUSTOMER_EXPORT = 'customer_export',

    SUPPLIER_VIEW = 'supplier_view',
    SUPPLIER_CREATE = 'supplier_create',
    SUPPLIER_EDIT = 'supplier_edit',
    SUPPLIER_DELETE = 'supplier_delete',
    SUPPLIER_IMPORT = 'supplier_import',
    SUPPLIER_EXPORT = 'supplier_export',

    REPORT_VIEW = 'report_view',

    VOUCHER_VIEW = 'voucher_view',
    VOUCHER_CREATE = 'voucher_create',
    VOUCHER_EDIT = 'voucher_edit',
    VOUCHER_DELETE = 'voucher_delete',

    // Golf
    GOLF_VIEW = 'golf_view',
    GOLF_MANAGE = 'golf_manage',
    GOLF_CHECKOUT = 'golf_checkout',
    GOLF_MEMBERSHIP = 'golf_membership',
    GOLF_REPORT = 'golf_report',
    GOLF_LINE_MANAGE = 'golf_line_manage',
}
